version: "3"

services:
  app:
    build: .docker 
    entrypoint: .docker/entrypoint.sh
    container_name: training-nestjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  
